name: build
on:
  push:
    branch:
      - main
jobs:
  DigaOla:
    runs-on: ubunto-latest
    steps:
      - run: echo "ola"
    Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v2
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: 'gradle'
        - run: ./gradlew build --no-daemon


