on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
 
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
 
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
 
      - name: Set Gradle Permission
        run: chmod +x ./gradlew
 
      - name: Build com Gradle
        run: ./gradlew build
 
      - name: Executar testes
        run: ./gradlew test